// ============================================================
// RITZ CARLTON BAL HARBOUR — POOL #1004 — DATA FILE
// AUTO-GENERATED by sync.py — do not edit directly
// Last synced: 2026-03-30 15:51:02
// To update: edit the XLSX in Google Drive, then run sync.py
// ============================================================

const BUDGET_DATA = [
  // ──────────────────────────────────────────────────────
  // 179 DESIGN
  // ──────────────────────────────────────────────────────
  {vendor:"179 DESIGN", code:"BA-01", desc:"Table Base (Banquette Dining Table)", isShip:false, budQty:2.0, unit:"ea", budUnitCost:325.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"BA-02", desc:"Table Base (Wood Two Top Table)", isShip:false, budQty:9.0, unit:"ea", budUnitCost:125.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"BE-04", desc:"Double Chaise Sun Lounge - Pool Area (White Frame)", isShip:false, budQty:6.0, unit:"ea", budUnitCost:3400.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"BE-05", desc:"Double Chaise Sun Lounge - Members Area (Brown Frame)", isShip:false, budQty:10.0, unit:"ea", budUnitCost:3400.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"CG-02", desc:"Rolling Waiter Station", isShip:false, budQty:2.0, unit:"ea", budUnitCost:4000.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"CG-03", desc:"Reception Desk", isShip:false, budQty:1.0, unit:"ea", budUnitCost:11200.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"CG-05", desc:"Reception Desk", isShip:false, budQty:1.0, unit:"ea", budUnitCost:7300.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"CG-06", desc:"Reception Credenza", isShip:false, budQty:1.0, unit:"ea", budUnitCost:8500.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"TB-03", desc:"Table 4 Top 36\"x36\" (6+1 extra)", isShip:false, budQty:7.0, unit:"ea", budUnitCost:850.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"TB-04", desc:"Table 2 Top Rectangle (7+2 extra)", isShip:false, budQty:9.0, unit:"ea", budUnitCost:550.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"TB-14", desc:"Side Table (VIP Cabana)", isShip:false, budQty:6.0, unit:"ea", budUnitCost:239.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"TB-15", desc:"Cocktail Table Top 30\"Dx42\"H (3+1 extra)", isShip:false, budQty:4.0, unit:"ea", budUnitCost:750.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // AMAZON
  // ──────────────────────────────────────────────────────
  {vendor:"AMAZON", code:"AC-13", desc:"Garbage Can (Bathroom)", isShip:false, budQty:2.0, unit:"ea", budUnitCost:200.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"AMAZON", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // AMERICAN UPHOLSTERY
  // ──────────────────────────────────────────────────────
  {vendor:"AMERICAN UPHOLSTERY", code:"BQ-2", desc:"Banquette Curved", isShip:false, budQty:2.0, unit:"ea", budUnitCost:8789.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"AMERICAN UPHOLSTERY", code:"BQ-3", desc:"Planter Banquette", isShip:false, budQty:1.0, unit:"ea", budUnitCost:28094.5, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"AMERICAN UPHOLSTERY", code:"FA-04", desc:"Tropicalia Fabric (Coral)", isShip:false, budQty:16.0, unit:"yd", budUnitCost:104.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"AMERICAN UPHOLSTERY", code:"FA-28", desc:"Sunbrella Canvas White", isShip:false, budQty:4.0, unit:"yd", budUnitCost:22.99, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"AMERICAN UPHOLSTERY", code:"FA-39", desc:"Last Splash - Willow Tree", isShip:false, budQty:28.0, unit:"yd", budUnitCost:57.88, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"AMERICAN UPHOLSTERY", code:"FA-40", desc:"Giza - Celadon", isShip:false, budQty:12.0, unit:"yd", budUnitCost:49.9, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"AMERICAN UPHOLSTERY", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // BLONDIE'S TREEHOUSE
  // ──────────────────────────────────────────────────────
  {vendor:"BLONDIE\'S TREEHOUSE", code:"SF-01", desc:"Artificial Foliage and Branches", isShip:false, budQty:1.0, unit:"ea", budUnitCost:245280.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"Shipping inclusive in price"},
  {vendor:"BLONDIE\'S TREEHOUSE", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // BROWN JORDAN
  // ──────────────────────────────────────────────────────
  {vendor:"BROWN JORDAN", code:"AC-03", desc:"Ottoman Pouf", isShip:false, budQty:4.0, unit:"ea", budUnitCost:467.93, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"BROWN JORDAN", code:"CH-14", desc:"Lounge Chair", isShip:false, budQty:12.0, unit:"ea", budUnitCost:1342.35, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"BROWN JORDAN", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // DECOSCAPE
  // ──────────────────────────────────────────────────────
  {vendor:"DECOSCAPE", code:"CH-13", desc:"Sectional Sofa - Single Cabana", isShip:false, budQty:6.0, unit:"ea", budUnitCost:3900.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"Link new fabrics"},
  {vendor:"DECOSCAPE", code:"CH-17", desc:"Stackable Chaise Lounge", isShip:false, budQty:100.0, unit:"ea", budUnitCost:570.95, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"Metal finish/sling color TBD"},
  {vendor:"DECOSCAPE", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // ERICA SHAMROCK
  // ──────────────────────────────────────────────────────
  {vendor:"ERICA SHAMROCK", code:"FA-15", desc:"Retro Runner Ivy", isShip:false, budQty:546.0, unit:"yd", budUnitCost:51.67, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"ERICA SHAMROCK", code:"FA-36", desc:"Last Splash - Willow Tree", isShip:false, budQty:118.25, unit:"yd", budUnitCost:57.88, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"ERICA SHAMROCK", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // FIBERBUILT
  // ──────────────────────────────────────────────────────
  {vendor:"FIBERBUILT", code:"UM-08", desc:"Octagon Beach Umbrella (7.5FT)", isShip:false, budQty:50.0, unit:"ea", budUnitCost:314.5, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"FIBERBUILT", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // FLORIDA SEATING
  // ──────────────────────────────────────────────────────
  {vendor:"FLORIDA SEATING", code:"TB-16", desc:"Side Table", isShip:false, budQty:50.0, unit:"ea", budUnitCost:152.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"FLORIDA SEATING", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // HOLLAND AND SHERRY
  // ──────────────────────────────────────────────────────
  {vendor:"HOLLAND AND SHERRY", code:"FA-17", desc:"Holland and Sherry Genoa Kir Royale", isShip:false, budQty:12.0, unit:"yd", budUnitCost:150.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"HOLLAND AND SHERRY", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // HOMEY CUSHION
  // ──────────────────────────────────────────────────────
  {vendor:"HOMEY CUSHION", code:"CU-01", desc:"Cushion Single Chaise Lounge (1.5\" or 2\" thick)", isShip:false, budQty:80.0, unit:"ea", budUnitCost:110.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"HOMEY CUSHION", code:"CU-02", desc:"Cushion Covers Single Chaise Lounge", isShip:false, budQty:10.0, unit:"ea", budUnitCost:50.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"HOMEY CUSHION", code:"FA-18", desc:"Canvas Seasalt", isShip:false, budQty:0.0, unit:"yd", budUnitCost:0.0, budExtCost:0.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"No cost listed — confirm"},
  {vendor:"HOMEY CUSHION", code:"PI-05", desc:"Head Pillows", isShip:false, budQty:32.0, unit:"ea", budUnitCost:80.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"Awaiting Peter specs"},
  {vendor:"HOMEY CUSHION", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // INSIGHT CORDLESS LIGHTING
  // ──────────────────────────────────────────────────────
  {vendor:"INSIGHT CORDLESS LIGHTING", code:"LT-01", desc:"Cordless Table Lamp", isShip:false, budQty:20.0, unit:"ea", budUnitCost:118.8, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"INSIGHT CORDLESS LIGHTING", code:"LT-02", desc:"Qi Charging Trolley (24 Lamps)", isShip:false, budQty:1.0, unit:"ea", budUnitCost:652.5, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"INSIGHT CORDLESS LIGHTING", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // JANUS ET CIE
  // ──────────────────────────────────────────────────────
  {vendor:"JANUS ET CIE", code:"CH-05", desc:"Single Chaise Lounger Stackable Frame Only", isShip:false, budQty:60.0, unit:"ea", budUnitCost:542.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"JANUS ET CIE", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // LEDGE
  // ──────────────────────────────────────────────────────
  {vendor:"LEDGE", code:"CH-16", desc:"In Pool Loungers", isShip:false, budQty:2.0, unit:"ea", budUnitCost:1299.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"LEDGE", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // LIGHTS ONLINE
  // ──────────────────────────────────────────────────────
  {vendor:"LIGHTS ONLINE", code:"EQ-06", desc:"Ceiling Fan", isShip:false, budQty:6.0, unit:"ea", budUnitCost:349.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"LIGHTS ONLINE", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // LUMENS
  // ──────────────────────────────────────────────────────
  {vendor:"LUMENS", code:"EQ-04", desc:"Fan Dining Pergola", isShip:false, budQty:5.0, unit:"ea", budUnitCost:579.95, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"LUMENS", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // PALECEK
  // ──────────────────────────────────────────────────────
  {vendor:"PALECEK", code:"CH-03", desc:"Dining Chair Armless (8+4 extra)", isShip:false, budQty:12.0, unit:"ea", budUnitCost:617.05, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"PALECEK", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // PRESTWICK LIMITED
  // ──────────────────────────────────────────────────────
  {vendor:"PRESTWICK LIMITED", code:"AC-22", desc:"Garbage Can - Central Area", isShip:false, budQty:1.0, unit:"ea", budUnitCost:1200.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"PRESTWICK LIMITED", code:"CG-04", desc:"Towel Drop Bucket", isShip:false, budQty:1.0, unit:"ea", budUnitCost:1600.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"PRESTWICK LIMITED", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // PROIMI OUTDOOR/INDOOR FURNITURE
  // ──────────────────────────────────────────────────────
  {vendor:"PROIMI OUTDOOR/INDOOR FURNITURE", code:"LTA-01", desc:"Pendant", isShip:false, budQty:1.0, unit:"ea", budUnitCost:1645.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"PROIMI OUTDOOR/INDOOR FURNITURE", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // RH
  // ──────────────────────────────────────────────────────
  {vendor:"RH", code:"AC-04", desc:"Planters Medium (North Lawn) 27\"x23\"", isShip:false, budQty:4.0, unit:"ea", budUnitCost:384.14, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"AC-05", desc:"Planters (20\"x32\")", isShip:false, budQty:10.0, unit:"ea", budUnitCost:354.69, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"AC-06", desc:"Planters Medium (24\"x24\")", isShip:false, budQty:3.0, unit:"ea", budUnitCost:378.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"AC-15", desc:"Planters Small (18\"x18\")", isShip:false, budQty:3.0, unit:"ea", budUnitCost:200.97, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"AC-16", desc:"Planters (20\"x48\")", isShip:false, budQty:5.0, unit:"ea", budUnitCost:502.38, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"AC-20", desc:"Planters Small (North Lawn) 20\"x17\"", isShip:false, budQty:3.0, unit:"ea", budUnitCost:310.01, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"CH-01", desc:"Bar Stool (19+4 extra)", isShip:false, budQty:23.0, unit:"ea", budUnitCost:678.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"CH-07", desc:"Stackable Single Chaise Lounge (44+4 extra)", isShip:false, budQty:60.0, unit:"ea", budUnitCost:925.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"CH-09", desc:"Lounge Chair", isShip:false, budQty:12.0, unit:"ea", budUnitCost:918.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"CH-11", desc:"Sofa", isShip:false, budQty:4.0, unit:"ea", budUnitCost:1620.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"CH-12", desc:"Barrel Dining Armchair Frame Only (28+4 extra)", isShip:false, budQty:32.0, unit:"ea", budUnitCost:525.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"FA-12", desc:"Cushion Single Chaise Lounge (Members Area)", isShip:false, budQty:60.0, unit:"ea", budUnitCost:570.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"FA-19", desc:"Barrel Dining Chair Cushions (COM)", isShip:false, budQty:32.0, unit:"ea", budUnitCost:186.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"FA-20", desc:"Bar Stool Cushions", isShip:false, budQty:23.0, unit:"ea", budUnitCost:233.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"FA-24", desc:"Sofa Cushion (Bloom Sofa)", isShip:false, budQty:4.0, unit:"ea", budUnitCost:812.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"FA-25", desc:"Chair Cushions (Bloom Lounge)", isShip:false, budQty:12.0, unit:"ea", budUnitCost:306.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"FA-33", desc:"Barrel Dining Chair Cushion Covers (COM)", isShip:false, budQty:5.0, unit:"ea", budUnitCost:186.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"FA-34", desc:"Bar Stool Cushion Covers Only", isShip:false, budQty:5.0, unit:"ea", budUnitCost:201.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"TB-01", desc:"Coffee Table 36\"", isShip:false, budQty:3.0, unit:"ea", budUnitCost:873.76, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"TB-11", desc:"Coffee Table Rectangle (52\")", isShip:false, budQty:4.0, unit:"ea", budUnitCost:1535.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"TB-13", desc:"Coffee Table Round 36\"", isShip:false, budQty:1.0, unit:"ea", budUnitCost:1687.24, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // STONEYARD INC.
  // ──────────────────────────────────────────────────────
  {vendor:"STONEYARD INC.", code:"CH-18", desc:"Stone Bench", isShip:false, budQty:1.0, unit:"ea", budUnitCost:3000.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"STONEYARD INC.", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // TBD
  // ──────────────────────────────────────────────────────
  {vendor:"TBD", code:"AE-03", desc:"Cabana 10\'x10\' (Existing on property)", isShip:false, budQty:0.0, unit:"ea", budUnitCost:0.0, budExtCost:0.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"Existing — no cost"},
  {vendor:"TBD", code:"CG-01", desc:"Credenza (Cabana)", isShip:false, budQty:6.0, unit:"ea", budUnitCost:2900.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"Vendor TBD"},
  {vendor:"TBD", code:"CH-19", desc:"Single Chaise Lounge Stackable Frame (Existing)", isShip:false, budQty:0.0, unit:"ea", budUnitCost:0.0, budExtCost:0.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"Existing — no cost"},
  {vendor:"TBD", code:"PI-06", desc:"Cabana Pillows", isShip:false, budQty:6.0, unit:"ea", budUnitCost:750.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"Specs TBD"},
  {vendor:"TBD", code:"PI-10", desc:"Head Pillows (Extra)", isShip:false, budQty:10.0, unit:"ea", budUnitCost:80.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TBD", code:"PI-11", desc:"Throw Pillows - Lulu Day Lounge", isShip:false, budQty:3.0, unit:"ea", budUnitCost:750.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TBD", code:"TB-05", desc:"Table Top Stone (48\"D)", isShip:false, budQty:2.0, unit:"ea", budUnitCost:2950.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"Supplier: EurAsia or 179"},
  {vendor:"TBD", code:"TB-07", desc:"Four Post Bed Side Table (Deco Scape)", isShip:false, budQty:3.0, unit:"ea", budUnitCost:950.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"Confirm white unit"},
  {vendor:"TBD", code:"TB-17", desc:"Double Chaise Lounge Side Table - Main Pool Deck", isShip:false, budQty:6.0, unit:"ea", budUnitCost:950.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TBD", code:"TB-18", desc:"Coffee Table (Single Cabana)", isShip:false, budQty:6.0, unit:"ea", budUnitCost:339.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TBD", code:"TB-19", desc:"Double Chaise Lounge Side Table - Members Area", isShip:false, budQty:10.0, unit:"ea", budUnitCost:950.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TBD", code:"UM-10", desc:"Tuuci Umbrella Frames Hex 8.5\' (Existing)", isShip:false, budQty:0.0, unit:"ea", budUnitCost:0.0, budExtCost:0.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"Existing — no cost"},
  {vendor:"TBD", code:"UMB-10", desc:"Aluma-Crete Anchor Wheels White (Existing)", isShip:false, budQty:0.0, unit:"ea", budUnitCost:0.0, budExtCost:0.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"Existing — no cost"},
  {vendor:"TBD", code:"WD-01", desc:"Front Facia (Flexible Thermal Wood Panels)", isShip:false, budQty:6.0, unit:"ea", budUnitCost:350.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TBD", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // TEDDY'S CUSTOM MARINE SEWING
  // ──────────────────────────────────────────────────────
  {vendor:"TEDDY\'S CUSTOM MARINE SEWING", code:"FA-21", desc:"Cushion Single Chaise Lounge", isShip:false, budQty:100.0, unit:"ea", budUnitCost:500.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"Awaiting Peter specs"},
  {vendor:"TEDDY\'S CUSTOM MARINE SEWING", code:"FA-35", desc:"Dining Chair Armless Cushion Covers", isShip:false, budQty:5.0, unit:"ea", budUnitCost:200.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TEDDY\'S CUSTOM MARINE SEWING", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // TUUCI
  // ──────────────────────────────────────────────────────
  {vendor:"TUUCI", code:"PE-01", desc:"PE Drawings Cabana", isShip:false, budQty:1.0, unit:"ea", budUnitCost:7500.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"Separate budget line — no shipping"},
  {vendor:"TUUCI", code:"AC-19", desc:"Planters (Rectangular on Wheels)", isShip:false, budQty:5.0, unit:"ea", budUnitCost:1057.05, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"AC-21", desc:"9\"x9\" Stainless Steel Surface Anchor", isShip:false, budQty:12.0, unit:"ea", budUnitCost:405.92, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"AE-01", desc:"Cabana 10\'x10\' (New)", isShip:false, budQty:3.0, unit:"ea", budUnitCost:15232.05, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"BE-01", desc:"Four Post Bed (Lulu Day Lounge)", isShip:false, budQty:3.0, unit:"ea", budUnitCost:10080.45, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"PC-01 OPT2", desc:"Replacement Roof Top for Existing Cabanas", isShip:false, budQty:3.0, unit:"ea", budUnitCost:5522.17, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:"If screws can\'t be removed"},
  {vendor:"TUUCI", code:"UM-02", desc:"Tuuci Umbrella Square Cantilever - Pool Area Main", isShip:false, budQty:6.0, unit:"ea", budUnitCost:4843.8, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UM-03", desc:"Tuuci Canvas (Hex)", isShip:false, budQty:36.0, unit:"ea", budUnitCost:718.06, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UM-05", desc:"Tuuci Umbrella 11.0\'", isShip:false, budQty:3.0, unit:"ea", budUnitCost:3784.73, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UM-06", desc:"Tuuci Umbrella 8.5\'", isShip:false, budQty:5.0, unit:"ea", budUnitCost:3464.78, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UM-07", desc:"Tuuci Umbrella Hex Center Post - Members Area Aluma Teak", isShip:false, budQty:20.0, unit:"ea", budUnitCost:1194.74, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UM-09", desc:"Tuuci Umbrella Square Cantilever - Members Area", isShip:false, budQty:10.0, unit:"ea", budUnitCost:4843.8, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UM-11", desc:"Tuuci Umbrella Hex Center Post - White Finish", isShip:false, budQty:1.0, unit:"ea", budUnitCost:1194.74, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UM-12", desc:"Tuuci Umbrella Hex Center Post - White Finish", isShip:false, budQty:4.0, unit:"ea", budUnitCost:1194.74, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UMB-01", desc:"G-Plate Stack Combo 400lbs", isShip:false, budQty:3.0, unit:"ea", budUnitCost:1267.65, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UMB-02", desc:"In-Ground Security Mount Anchor Cantilever Pool Deck Main", isShip:false, budQty:6.0, unit:"ea", budUnitCost:354.38, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UMB-04", desc:"Aluma-Crete Anchor 150lbs Wheels", isShip:false, budQty:5.0, unit:"ea", budUnitCost:492.08, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UMB-05", desc:"G-Plate Stack Combo 600lbs Cantilever Members Area", isShip:false, budQty:10.0, unit:"ea", budUnitCost:1723.28, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UMB-06", desc:"Aluma-Crete Anchor 150lbs Wheels - White Finish", isShip:false, budQty:10.0, unit:"ea", budUnitCost:437.4, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UMB-07", desc:"Aluma-Crete Anchor 150lbs Wheels - Aluma Teak Finish", isShip:false, budQty:20.0, unit:"ea", budUnitCost:492.08, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UMB-11", desc:"Aluma-Crete Anchor 150lbs Wheels - White Finish Flex Area", isShip:false, budQty:4.0, unit:"ea", budUnitCost:437.4, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"WT-01", desc:"Cabana Curtains for Existing Cabanas (per side)", isShip:false, budQty:3.0, unit:"ea", budUnitCost:826.2, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // WALTERS WICKER
  // ──────────────────────────────────────────────────────
  {vendor:"WALTERS WICKER", code:"TB-06", desc:"Side Table", isShip:false, budQty:70.0, unit:"ea", budUnitCost:298.0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"WALTERS WICKER", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // WEST ELM
  // ──────────────────────────────────────────────────────
  {vendor:"WEST ELM", code:"AC-18", desc:"Planters Pot (13\"x9\")", isShip:false, budQty:2.0, unit:"ea", budUnitCost:71.2, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
  {vendor:"WEST ELM", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:0, budHiComm:0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:0, balHiComm:0, status:"Not Started", eta:"", notes:""},
];

const PROJECT_FIXED = {
  storage_installation: 75000.00,
  blondies_shipping_credit: -24528.00,
  sales_tax_rate: 0.07,
  shipping_rate: 0.10,
  commission_rate: 0.10,
};
