// ============================================================
// RITZ CARLTON BAL HARBOUR — POOL #1004 — DATA FILE
// AUTO-GENERATED by sync.py — do not edit directly
// Last synced: 2026-03-30 17:12:20
// To update: edit the XLSX in Google Drive, then run sync.py
// ============================================================

const BUDGET_DATA = [
  // ──────────────────────────────────────────────────────
  // 179 DESIGN
  // ──────────────────────────────────────────────────────
  {vendor:"179 DESIGN", code:"BA-01", desc:"Table Base (Banquette Dining Table)", isShip:false, budQty:2.0, unit:"ea", budUnitCost:325.0, budExtCost:650.0, budHiComm:65.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:650.0, balHiComm:65.0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"BA-02", desc:"Table Base (Wood Two Top Table)", isShip:false, budQty:9.0, unit:"ea", budUnitCost:125.0, budExtCost:1125.0, budHiComm:112.5, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1125.0, balHiComm:112.5, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"BE-04", desc:"Double Chaise Sun Lounge - Pool Area (White Frame and Cushion)", isShip:false, budQty:6.0, unit:"ea", budUnitCost:3400.0, budExtCost:20400.0, budHiComm:2040.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:20400.0, balHiComm:2040.0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"BE-05", desc:"Double Chaise Sun Lounge - Members Area (Brown Frame and Cushion)", isShip:false, budQty:10.0, unit:"ea", budUnitCost:3400.0, budExtCost:34000.0, budHiComm:3400.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:34000.0, balHiComm:3400.0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"CG-02", desc:"Rolling Waiter Station", isShip:false, budQty:2.0, unit:"ea", budUnitCost:4000.0, budExtCost:8000.0, budHiComm:800.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:8000.0, balHiComm:800.0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"CG-03", desc:"Reception Desk", isShip:false, budQty:1.0, unit:"ea", budUnitCost:11200.0, budExtCost:11200.0, budHiComm:1120.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:11200.0, balHiComm:1120.0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"CG-05", desc:"Reception Desk", isShip:false, budQty:1.0, unit:"ea", budUnitCost:7300.0, budExtCost:7300.0, budHiComm:730.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:7300.0, balHiComm:730.0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"CG-06", desc:"Reception Credenza", isShip:false, budQty:1.0, unit:"ea", budUnitCost:8500.0, budExtCost:8500.0, budHiComm:850.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:8500.0, balHiComm:850.0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"CH-13", desc:"Sectional Sofa - Single Cabana", isShip:false, budQty:6.0, unit:"ea", budUnitCost:3600.0, budExtCost:21600.0, budHiComm:2160.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:21600.0, balHiComm:2160.0, status:"Not Started", eta:"", notes:"Moved from Decoscape"},
  {vendor:"179 DESIGN", code:"TB-03", desc:"Table 4 Top (36\" x 36\") (6 + 1 extra)", isShip:false, budQty:7.0, unit:"ea", budUnitCost:850.0, budExtCost:5950.0, budHiComm:595.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:5950.0, balHiComm:595.0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"TB-04", desc:"Table 2 Top Rectangle (7 + 2 extra)", isShip:false, budQty:9.0, unit:"ea", budUnitCost:550.0, budExtCost:4950.0, budHiComm:495.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:4950.0, balHiComm:495.0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"TB-14", desc:"Side Table (VIP Cabana)", isShip:false, budQty:6.0, unit:"ea", budUnitCost:239.0, budExtCost:1434.0, budHiComm:143.4, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1434.0, balHiComm:143.4, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"TB-15", desc:"Cocktail Table Top (30\"D x 42\"H) (3 + 1 extra)", isShip:false, budQty:4.0, unit:"ea", budUnitCost:750.0, budExtCost:3000.0, budHiComm:300.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:3000.0, balHiComm:300.0, status:"Not Started", eta:"", notes:""},
  {vendor:"179 DESIGN", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:12810.9, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:12810.9, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // AMAZON
  // ──────────────────────────────────────────────────────
  {vendor:"AMAZON", code:"AC-13", desc:"Garbage Can (Bathroom)", isShip:false, budQty:2.0, unit:"ea", budUnitCost:200.0, budExtCost:400.0, budHiComm:40.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:400.0, balHiComm:40.0, status:"Not Started", eta:"", notes:""},
  {vendor:"AMAZON", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:40.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:40.0, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // AMERICAN UPHOLSTERY
  // ──────────────────────────────────────────────────────
  {vendor:"AMERICAN UPHOLSTERY", code:"BQ-2", desc:"Banquette Curved", isShip:false, budQty:2.0, unit:"ea", budUnitCost:8789.0, budExtCost:17578.0, budHiComm:1757.8, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:17578.0, balHiComm:1757.8, status:"Not Started", eta:"", notes:""},
  {vendor:"AMERICAN UPHOLSTERY", code:"BQ-3", desc:"Planter Banquette", isShip:false, budQty:1.0, unit:"ea", budUnitCost:28094.5, budExtCost:28094.5, budHiComm:2809.45, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:28094.5, balHiComm:2809.45, status:"Not Started", eta:"", notes:""},
  {vendor:"AMERICAN UPHOLSTERY", code:"FA-04", desc:"Tropicalia Fabric (Coral)", isShip:false, budQty:16.0, unit:"yd", budUnitCost:104.0, budExtCost:1664.0, budHiComm:166.4, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1664.0, balHiComm:166.4, status:"Not Started", eta:"", notes:""},
  {vendor:"AMERICAN UPHOLSTERY", code:"FA-09", desc:"Last Splash - Pink Grapefruit", isShip:false, budQty:0.0, unit:"yd", budUnitCost:0.0, budExtCost:0.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0.0, balHiComm:0.0, status:"Not Started", eta:"", notes:""},
  {vendor:"AMERICAN UPHOLSTERY", code:"FA-28", desc:"Sunbrella Canvas White", isShip:false, budQty:4.0, unit:"yd", budUnitCost:22.99, budExtCost:91.96, budHiComm:9.2, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:91.96, balHiComm:9.2, status:"Not Started", eta:"", notes:""},
  {vendor:"AMERICAN UPHOLSTERY", code:"FA-29", desc:"Seat Cushions (Planter Banquette)", isShip:false, budQty:0.0, unit:"ea", budUnitCost:0.0, budExtCost:0.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0.0, balHiComm:0.0, status:"Not Started", eta:"", notes:""},
  {vendor:"AMERICAN UPHOLSTERY", code:"FA-30", desc:"Seat Back (Planter Banquette)", isShip:false, budQty:0.0, unit:"ea", budUnitCost:0.0, budExtCost:0.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0.0, balHiComm:0.0, status:"Not Started", eta:"", notes:""},
  {vendor:"AMERICAN UPHOLSTERY", code:"FA-39", desc:"Last Splash - Willow Tree", isShip:false, budQty:28.0, unit:"yd", budUnitCost:57.88, budExtCost:1620.64, budHiComm:162.06, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1620.64, balHiComm:162.06, status:"Not Started", eta:"", notes:""},
  {vendor:"AMERICAN UPHOLSTERY", code:"FA-40", desc:"Giza - Celadon", isShip:false, budQty:12.0, unit:"yd", budUnitCost:49.9, budExtCost:598.8, budHiComm:59.88, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:598.8, balHiComm:59.88, status:"Not Started", eta:"", notes:""},
  {vendor:"AMERICAN UPHOLSTERY", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:4964.79, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:4964.79, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // BLONDIE'S TREEHOUSE INC.
  // ──────────────────────────────────────────────────────
  {vendor:"BLONDIE\'S TREEHOUSE INC.", code:"SF-01", desc:"Artificial Foliage and Branches", isShip:false, budQty:1.0, unit:"ea", budUnitCost:245280.0, budExtCost:245280.0, budHiComm:24528.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:245280.0, balHiComm:24528.0, status:"Not Started", eta:"", notes:"Shipping inclusive in price"},
  {vendor:"BLONDIE\'S TREEHOUSE INC.", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:24528.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:24528.0, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // BROWN JORDAN
  // ──────────────────────────────────────────────────────
  {vendor:"BROWN JORDAN", code:"AC-03", desc:"Ottoman Pouf", isShip:false, budQty:4.0, unit:"ea", budUnitCost:467.93, budExtCost:1871.72, budHiComm:187.17, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1871.72, balHiComm:187.17, status:"Not Started", eta:"", notes:""},
  {vendor:"BROWN JORDAN", code:"CH-14", desc:"Lounge Chair", isShip:false, budQty:12.0, unit:"ea", budUnitCost:1342.35, budExtCost:16108.2, budHiComm:1610.82, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:16108.2, balHiComm:1610.82, status:"Not Started", eta:"", notes:""},
  {vendor:"BROWN JORDAN", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:1797.99, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:1797.99, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // DECOSCAPE
  // ──────────────────────────────────────────────────────
  {vendor:"DECOSCAPE", code:"CH-17", desc:"Stackable Chaise Lounge (Metal Finish and Sling Color TBD)", isShip:false, budQty:100.0, unit:"ea", budUnitCost:570.95, budExtCost:57095.0, budHiComm:5709.5, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:57095.0, balHiComm:5709.5, status:"Not Started", eta:"", notes:"Metal finish/sling color TBD"},
  {vendor:"DECOSCAPE", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:5709.5, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:5709.5, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // ERICA SHAMROCK
  // ──────────────────────────────────────────────────────
  {vendor:"ERICA SHAMROCK", code:"FA-15", desc:"Retro Runner Ivy", isShip:false, budQty:546.0, unit:"yd", budUnitCost:51.67, budExtCost:28211.82, budHiComm:2821.18, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:28211.82, balHiComm:2821.18, status:"Not Started", eta:"", notes:""},
  {vendor:"ERICA SHAMROCK", code:"FA-36", desc:"Last Splash - Willow Tree", isShip:false, budQty:154.25, unit:"yd", budUnitCost:57.88, budExtCost:8927.99, budHiComm:892.8, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:8927.99, balHiComm:892.8, status:"Not Started", eta:"", notes:""},
  {vendor:"ERICA SHAMROCK", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:3713.98, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:3713.98, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // FIBERBUILT
  // ──────────────────────────────────────────────────────
  {vendor:"FIBERBUILT", code:"UM-08", desc:"Octagon Beach Umbrella (7.5FT)", isShip:false, budQty:50.0, unit:"ea", budUnitCost:314.5, budExtCost:15725.0, budHiComm:1572.5, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:15725.0, balHiComm:1572.5, status:"Not Started", eta:"", notes:""},
  {vendor:"FIBERBUILT", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:1572.5, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:1572.5, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // FLORIDA SEATING
  // ──────────────────────────────────────────────────────
  {vendor:"FLORIDA SEATING", code:"TB-16", desc:"Side Table", isShip:false, budQty:50.0, unit:"ea", budUnitCost:152.0, budExtCost:7600.0, budHiComm:760.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:7600.0, balHiComm:760.0, status:"Not Started", eta:"", notes:""},
  {vendor:"FLORIDA SEATING", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:760.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:760.0, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // HOLLAND AND SHERRY
  // ──────────────────────────────────────────────────────
  {vendor:"HOLLAND AND SHERRY", code:"FA-17", desc:"Holland and Sherry Genoa Kir Royale", isShip:false, budQty:12.0, unit:"yd", budUnitCost:150.0, budExtCost:1800.0, budHiComm:180.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1800.0, balHiComm:180.0, status:"Not Started", eta:"", notes:""},
  {vendor:"HOLLAND AND SHERRY", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:180.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:180.0, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // HOMEY CUSHION
  // ──────────────────────────────────────────────────────
  {vendor:"HOMEY CUSHION", code:"CU-01", desc:"Cushion Single Chaise Lounge (1.5\" or 2\" Thick)", isShip:false, budQty:80.0, unit:"ea", budUnitCost:110.0, budExtCost:8800.0, budHiComm:880.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:8800.0, balHiComm:880.0, status:"Not Started", eta:"", notes:""},
  {vendor:"HOMEY CUSHION", code:"CU-02", desc:"Cushion Covers Single Chaise Lounge", isShip:false, budQty:10.0, unit:"ea", budUnitCost:50.0, budExtCost:500.0, budHiComm:50.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:500.0, balHiComm:50.0, status:"Not Started", eta:"", notes:""},
  {vendor:"HOMEY CUSHION", code:"CU-03", desc:"Sectional Sofa Cushions (Yards Per Unit Pending)", isShip:false, budQty:6.0, unit:"ea", budUnitCost:295.0, budExtCost:1770.0, budHiComm:177.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1770.0, balHiComm:177.0, status:"Not Started", eta:"", notes:""},
  {vendor:"HOMEY CUSHION", code:"CU-04", desc:"Cushion Single Chaise Lounge (Peter to provide specs and Sunbrella fabric)", isShip:false, budQty:100.0, unit:"ea", budUnitCost:200.0, budExtCost:20000.0, budHiComm:2000.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:20000.0, balHiComm:2000.0, status:"Not Started", eta:"", notes:"Awaiting Peter specs"},
  {vendor:"HOMEY CUSHION", code:"FA-18", desc:"Canvas Seasalt (Piping for Sun Loungers)", isShip:false, budQty:0.0, unit:"yd", budUnitCost:0.0, budExtCost:0.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0.0, balHiComm:0.0, status:"Not Started", eta:"", notes:"No cost listed"},
  {vendor:"HOMEY CUSHION", code:"PI-05", desc:"Head Pillows (Peter to provide pillow specs)", isShip:false, budQty:32.0, unit:"ea", budUnitCost:80.0, budExtCost:2560.0, budHiComm:256.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:2560.0, balHiComm:256.0, status:"Not Started", eta:"", notes:"Awaiting Peter specs"},
  {vendor:"HOMEY CUSHION", code:"PI-10", desc:"Head Pillows (Extra)", isShip:false, budQty:10.0, unit:"ea", budUnitCost:80.0, budExtCost:800.0, budHiComm:80.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:800.0, balHiComm:80.0, status:"Not Started", eta:"", notes:""},
  {vendor:"HOMEY CUSHION", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:3443.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:3443.0, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // INSIGHT CORDLESS LIGHTING
  // ──────────────────────────────────────────────────────
  {vendor:"INSIGHT CORDLESS LIGHTING", code:"LT-01", desc:"Cordless Table Lamp", isShip:false, budQty:20.0, unit:"ea", budUnitCost:118.8, budExtCost:2376.0, budHiComm:237.6, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:2376.0, balHiComm:237.6, status:"Not Started", eta:"", notes:""},
  {vendor:"INSIGHT CORDLESS LIGHTING", code:"LT-02", desc:"Qi Charging Trolley (Charges 24 Lamps)", isShip:false, budQty:1.0, unit:"ea", budUnitCost:652.5, budExtCost:652.5, budHiComm:65.25, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:652.5, balHiComm:65.25, status:"Not Started", eta:"", notes:""},
  {vendor:"INSIGHT CORDLESS LIGHTING", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:302.85, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:302.85, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // JANUS ET CIE
  // ──────────────────────────────────────────────────────
  {vendor:"JANUS ET CIE", code:"CH-05", desc:"Single Chaise Lounger - Stackable - Frame Only", isShip:false, budQty:60.0, unit:"ea", budUnitCost:542.0, budExtCost:32520.0, budHiComm:3252.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:32520.0, balHiComm:3252.0, status:"Not Started", eta:"", notes:""},
  {vendor:"JANUS ET CIE", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:3252.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:3252.0, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // LEDGE
  // ──────────────────────────────────────────────────────
  {vendor:"LEDGE", code:"CH-16", desc:"In Pool Loungers", isShip:false, budQty:2.0, unit:"ea", budUnitCost:1299.0, budExtCost:2598.0, budHiComm:259.8, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:2598.0, balHiComm:259.8, status:"Not Started", eta:"", notes:""},
  {vendor:"LEDGE", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:259.8, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:259.8, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // LIGHTS ONLINE
  // ──────────────────────────────────────────────────────
  {vendor:"LIGHTS ONLINE", code:"EQ-06", desc:"Ceiling Fan", isShip:false, budQty:6.0, unit:"ea", budUnitCost:349.0, budExtCost:2094.0, budHiComm:209.4, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:2094.0, balHiComm:209.4, status:"Not Started", eta:"", notes:""},
  {vendor:"LIGHTS ONLINE", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:209.4, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:209.4, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // LUMENS
  // ──────────────────────────────────────────────────────
  {vendor:"LUMENS", code:"EQ-04", desc:"Fan Dining Pergola", isShip:false, budQty:5.0, unit:"ea", budUnitCost:579.95, budExtCost:2899.75, budHiComm:289.98, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:2899.75, balHiComm:289.98, status:"Not Started", eta:"", notes:""},
  {vendor:"LUMENS", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:289.98, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:289.98, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // PALECEK
  // ──────────────────────────────────────────────────────
  {vendor:"PALECEK", code:"CH-03", desc:"Dining Chair Armless (8 + 4 extra)", isShip:false, budQty:12.0, unit:"ea", budUnitCost:617.05, budExtCost:7404.6, budHiComm:740.46, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:7404.6, balHiComm:740.46, status:"Not Started", eta:"", notes:""},
  {vendor:"PALECEK", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:740.46, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:740.46, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // PRESTWICK LIMITED
  // ──────────────────────────────────────────────────────
  {vendor:"PRESTWICK LIMITED", code:"AC-22", desc:"Garbage Can - Central Area", isShip:false, budQty:1.0, unit:"ea", budUnitCost:1200.0, budExtCost:1200.0, budHiComm:120.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1200.0, balHiComm:120.0, status:"Not Started", eta:"", notes:""},
  {vendor:"PRESTWICK LIMITED", code:"CG-04", desc:"Towel Drop Bucket", isShip:false, budQty:1.0, unit:"ea", budUnitCost:1600.0, budExtCost:1600.0, budHiComm:160.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1600.0, balHiComm:160.0, status:"Not Started", eta:"", notes:""},
  {vendor:"PRESTWICK LIMITED", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:280.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:280.0, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // PROIMI OUTDOOR/INDOOR FURNITURE
  // ──────────────────────────────────────────────────────
  {vendor:"PROIMI OUTDOOR/INDOOR FURNITURE", code:"LTA-01", desc:"Pendant", isShip:false, budQty:1.0, unit:"ea", budUnitCost:1645.0, budExtCost:1645.0, budHiComm:164.5, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1645.0, balHiComm:164.5, status:"Not Started", eta:"", notes:""},
  {vendor:"PROIMI OUTDOOR/INDOOR FURNITURE", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:164.5, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:164.5, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // RH
  // ──────────────────────────────────────────────────────
  {vendor:"RH", code:"AC-04", desc:"Planters Medium (North Lawn) 27\"x23\"", isShip:false, budQty:4.0, unit:"ea", budUnitCost:384.14, budExtCost:1536.56, budHiComm:153.66, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1536.56, balHiComm:153.66, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"AC-05", desc:"Planters (20\"x32\")", isShip:false, budQty:10.0, unit:"ea", budUnitCost:354.69, budExtCost:3546.9, budHiComm:354.69, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:3546.9, balHiComm:354.69, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"AC-06", desc:"Planters Medium (24\"x24\")", isShip:false, budQty:3.0, unit:"ea", budUnitCost:378.0, budExtCost:1134.0, budHiComm:113.4, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1134.0, balHiComm:113.4, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"AC-15", desc:"Planters Small (18\"x18\")", isShip:false, budQty:3.0, unit:"ea", budUnitCost:200.97, budExtCost:602.91, budHiComm:60.29, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:602.91, balHiComm:60.29, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"AC-16", desc:"Planters (20\"x48\")", isShip:false, budQty:5.0, unit:"ea", budUnitCost:502.38, budExtCost:2511.9, budHiComm:251.19, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:2511.9, balHiComm:251.19, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"AC-20", desc:"Planters Small (North Lawn) 20\"x17\"", isShip:false, budQty:3.0, unit:"ea", budUnitCost:310.01, budExtCost:930.03, budHiComm:93.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:930.03, balHiComm:93.0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"CH-01", desc:"Bar Stool (19 + 4 extra)", isShip:false, budQty:23.0, unit:"ea", budUnitCost:678.0, budExtCost:15594.0, budHiComm:1559.4, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:15594.0, balHiComm:1559.4, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"CH-07", desc:"Stackable Single Chaise Lounge (44 + 4 extra)", isShip:false, budQty:60.0, unit:"ea", budUnitCost:925.0, budExtCost:55500.0, budHiComm:5550.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:55500.0, balHiComm:5550.0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"CH-09", desc:"Lounge Chair", isShip:false, budQty:12.0, unit:"ea", budUnitCost:918.0, budExtCost:11016.0, budHiComm:1101.6, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:11016.0, balHiComm:1101.6, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"CH-11", desc:"Sofa", isShip:false, budQty:4.0, unit:"ea", budUnitCost:1620.0, budExtCost:6480.0, budHiComm:648.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:6480.0, balHiComm:648.0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"CH-12", desc:"Barrel Dining Armchair Frame Only (28 + 4 extra)", isShip:false, budQty:32.0, unit:"ea", budUnitCost:525.0, budExtCost:16800.0, budHiComm:1680.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:16800.0, balHiComm:1680.0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"FA-12", desc:"Cushion Single Chaise Lounge (Members Area)", isShip:false, budQty:60.0, unit:"ea", budUnitCost:570.0, budExtCost:34200.0, budHiComm:3420.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:34200.0, balHiComm:3420.0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"FA-19", desc:"Barrel Dining Chair Cushions (COM)", isShip:false, budQty:32.0, unit:"ea", budUnitCost:186.0, budExtCost:5952.0, budHiComm:595.2, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:5952.0, balHiComm:595.2, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"FA-20", desc:"Bar Stool Cushions", isShip:false, budQty:23.0, unit:"ea", budUnitCost:233.0, budExtCost:5359.0, budHiComm:535.9, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:5359.0, balHiComm:535.9, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"FA-24", desc:"Sofa Cushion (Bloom Sofa)", isShip:false, budQty:4.0, unit:"ea", budUnitCost:812.0, budExtCost:3248.0, budHiComm:324.8, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:3248.0, balHiComm:324.8, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"FA-25", desc:"Chair Cushions (Bloom Lounge)", isShip:false, budQty:12.0, unit:"ea", budUnitCost:306.0, budExtCost:3672.0, budHiComm:367.2, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:3672.0, balHiComm:367.2, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"FA-33", desc:"Barrel Dining Chair Cushion Covers (COM)", isShip:false, budQty:5.0, unit:"ea", budUnitCost:186.0, budExtCost:930.0, budHiComm:93.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:930.0, balHiComm:93.0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"FA-34", desc:"Bar Stool Cushion Covers Only", isShip:false, budQty:5.0, unit:"ea", budUnitCost:201.0, budExtCost:1005.0, budHiComm:100.5, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1005.0, balHiComm:100.5, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"TB-01", desc:"Coffee Table 36\"", isShip:false, budQty:3.0, unit:"ea", budUnitCost:873.76, budExtCost:2621.28, budHiComm:262.13, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:2621.28, balHiComm:262.13, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"TB-11", desc:"Coffee Table Rectangle (52\")", isShip:false, budQty:4.0, unit:"ea", budUnitCost:1535.0, budExtCost:6140.0, budHiComm:614.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:6140.0, balHiComm:614.0, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"TB-13", desc:"Coffee Table Round 36\"", isShip:false, budQty:1.0, unit:"ea", budUnitCost:1687.24, budExtCost:1687.24, budHiComm:168.72, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1687.24, balHiComm:168.72, status:"Not Started", eta:"", notes:""},
  {vendor:"RH", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:18046.68, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:18046.68, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // STONEYARD INC.
  // ──────────────────────────────────────────────────────
  {vendor:"STONEYARD INC.", code:"CH-18", desc:"Stone Bench", isShip:false, budQty:1.0, unit:"ea", budUnitCost:3000.0, budExtCost:3000.0, budHiComm:300.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:3000.0, balHiComm:300.0, status:"Not Started", eta:"", notes:""},
  {vendor:"STONEYARD INC.", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:300.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:300.0, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // TBD
  // ──────────────────────────────────────────────────────
  {vendor:"TBD", code:"AE-03", desc:"Cabana 10\'x10\' (Existing on property)", isShip:false, budQty:0.0, unit:"ea", budUnitCost:0.0, budExtCost:0.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0.0, balHiComm:0.0, status:"Not Started", eta:"", notes:"Existing — no cost"},
  {vendor:"TBD", code:"CG-01", desc:"Credenza (Cabana)", isShip:false, budQty:6.0, unit:"ea", budUnitCost:2900.0, budExtCost:17400.0, budHiComm:1740.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:17400.0, balHiComm:1740.0, status:"Not Started", eta:"", notes:"Vendor TBD"},
  {vendor:"TBD", code:"CH-19", desc:"Single Chaise Lounge Stackable Frame (Existing on property)", isShip:false, budQty:0.0, unit:"ea", budUnitCost:0.0, budExtCost:0.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0.0, balHiComm:0.0, status:"Not Started", eta:"", notes:"Existing — no cost"},
  {vendor:"TBD", code:"PI-06", desc:"Cabana Pillows (To be specified)", isShip:false, budQty:6.0, unit:"ea", budUnitCost:750.0, budExtCost:4500.0, budHiComm:450.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:4500.0, balHiComm:450.0, status:"Not Started", eta:"", notes:"Specs TBD"},
  {vendor:"TBD", code:"TB-05", desc:"Table Top Stone (48\"D) (Supplier: EurAsia or 179)", isShip:false, budQty:2.0, unit:"ea", budUnitCost:2950.0, budExtCost:5900.0, budHiComm:590.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:5900.0, balHiComm:590.0, status:"Not Started", eta:"", notes:""},
  {vendor:"TBD", code:"TB-07", desc:"Four Post Bed Side Table (Deco Scape) — confirm white unit", isShip:false, budQty:3.0, unit:"ea", budUnitCost:950.0, budExtCost:2850.0, budHiComm:285.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:2850.0, balHiComm:285.0, status:"Not Started", eta:"", notes:"Confirm white unit"},
  {vendor:"TBD", code:"TB-17", desc:"Double Chaise Lounge Side Table - Main Pool Deck", isShip:false, budQty:6.0, unit:"ea", budUnitCost:950.0, budExtCost:5700.0, budHiComm:570.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:5700.0, balHiComm:570.0, status:"Not Started", eta:"", notes:""},
  {vendor:"TBD", code:"TB-18", desc:"Coffee Table (Single Cabana)", isShip:false, budQty:6.0, unit:"ea", budUnitCost:339.0, budExtCost:2034.0, budHiComm:203.4, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:2034.0, balHiComm:203.4, status:"Not Started", eta:"", notes:""},
  {vendor:"TBD", code:"TB-19", desc:"Double Chaise Lounge Side Table - Members Area Pool Deck", isShip:false, budQty:10.0, unit:"ea", budUnitCost:950.0, budExtCost:9500.0, budHiComm:950.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:9500.0, balHiComm:950.0, status:"Not Started", eta:"", notes:""},
  {vendor:"TBD", code:"UM-10", desc:"Tuuci Umbrella Frames (White) - Hex 8.5\' (Existing on property)", isShip:false, budQty:0.0, unit:"ea", budUnitCost:0.0, budExtCost:0.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0.0, balHiComm:0.0, status:"Not Started", eta:"", notes:"Existing — no cost"},
  {vendor:"TBD", code:"UMB-10", desc:"Aluma-Crete Anchor (Wheels) White Finish (Existing on property)", isShip:false, budQty:0.0, unit:"ea", budUnitCost:0.0, budExtCost:0.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:0.0, balHiComm:0.0, status:"Not Started", eta:"", notes:"Existing — no cost"},
  {vendor:"TBD", code:"WD-01", desc:"Front Facia (Flexible Thermal Wood Panels)", isShip:false, budQty:6.0, unit:"ea", budUnitCost:350.0, budExtCost:2100.0, budHiComm:210.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:2100.0, balHiComm:210.0, status:"Not Started", eta:"", notes:""},
  {vendor:"TBD", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:4998.4, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:4998.4, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // TEDDY'S CUSTOM MARINE SEWING
  // ──────────────────────────────────────────────────────
  {vendor:"TEDDY\'S CUSTOM MARINE SEWING", code:"FA-35", desc:"Dining Chair Armless Cushion Covers", isShip:false, budQty:5.0, unit:"ea", budUnitCost:200.0, budExtCost:1000.0, budHiComm:100.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1000.0, balHiComm:100.0, status:"Not Started", eta:"", notes:""},
  {vendor:"TEDDY\'S CUSTOM MARINE SEWING", code:"PI-11", desc:"Throw Pillows - Lulu Day Lounge", isShip:false, budQty:3.0, unit:"ea", budUnitCost:750.0, budExtCost:2250.0, budHiComm:225.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:2250.0, balHiComm:225.0, status:"Not Started", eta:"", notes:""},
  {vendor:"TEDDY\'S CUSTOM MARINE SEWING", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:325.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:325.0, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // TUUCI
  // ──────────────────────────────────────────────────────
  {vendor:"TUUCI", code:"PE-01", desc:"PE Drawings Cabana", isShip:false, budQty:1.0, unit:"ea", budUnitCost:7500.0, budExtCost:7500.0, budHiComm:750.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:7500.0, balHiComm:750.0, status:"Not Started", eta:"", notes:"Separate budget line — no shipping"},
  {vendor:"TUUCI", code:"AC-19", desc:"Planters (Rectangular on Wheels)", isShip:false, budQty:5.0, unit:"ea", budUnitCost:1057.05, budExtCost:5285.25, budHiComm:528.52, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:5285.25, balHiComm:528.52, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"AC-21", desc:"9\"x9\" Stainless Steel Surface Anchor", isShip:false, budQty:12.0, unit:"ea", budUnitCost:405.92, budExtCost:4871.04, budHiComm:487.1, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:4871.04, balHiComm:487.1, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"AE-01", desc:"Cabana 10\'x10\' (New)", isShip:false, budQty:3.0, unit:"ea", budUnitCost:15232.05, budExtCost:45696.15, budHiComm:4569.61, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:45696.15, balHiComm:4569.61, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"BE-01", desc:"Four Post Bed (Lulu Day Lounge)", isShip:false, budQty:3.0, unit:"ea", budUnitCost:10080.45, budExtCost:30241.35, budHiComm:3024.14, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:30241.35, balHiComm:3024.14, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"PC-01 OPT2", desc:"Replacement Roof Top for Existing Cabanas (if screws cannot be removed)", isShip:false, budQty:3.0, unit:"ea", budUnitCost:5522.17, budExtCost:16566.51, budHiComm:1656.65, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:16566.51, balHiComm:1656.65, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UM-02", desc:"Tuuci Umbrella - Square (Cantilever) - Pool Area Main", isShip:false, budQty:6.0, unit:"ea", budUnitCost:4843.8, budExtCost:29062.8, budHiComm:2906.28, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:29062.8, balHiComm:2906.28, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UM-03", desc:"Tuuci Canvas (Hex)", isShip:false, budQty:36.0, unit:"ea", budUnitCost:718.06, budExtCost:25850.16, budHiComm:2585.02, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:25850.16, balHiComm:2585.02, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UM-05", desc:"Tuuci Umbrella - 11.0\'", isShip:false, budQty:3.0, unit:"ea", budUnitCost:3784.73, budExtCost:11354.19, budHiComm:1135.42, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:11354.19, balHiComm:1135.42, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UM-06", desc:"Tuuci Umbrella - 8.5\'", isShip:false, budQty:5.0, unit:"ea", budUnitCost:3464.78, budExtCost:17323.9, budHiComm:1732.39, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:17323.9, balHiComm:1732.39, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UM-07", desc:"Tuuci Umbrella - Hex (Center Post) - Members Area - Aluma Teak", isShip:false, budQty:20.0, unit:"ea", budUnitCost:1194.74, budExtCost:23894.8, budHiComm:2389.48, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:23894.8, balHiComm:2389.48, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UM-09", desc:"Tuuci Umbrella - Square (Cantilever) - Members Area", isShip:false, budQty:10.0, unit:"ea", budUnitCost:4843.8, budExtCost:48438.0, budHiComm:4843.8, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:48438.0, balHiComm:4843.8, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UM-11", desc:"Tuuci Umbrella - Hex (Center Post) - White Finish", isShip:false, budQty:1.0, unit:"ea", budUnitCost:1194.74, budExtCost:1194.74, budHiComm:119.47, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1194.74, balHiComm:119.47, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UM-12", desc:"Tuuci Umbrella - Hex (Center Post) - White Finish", isShip:false, budQty:4.0, unit:"ea", budUnitCost:1194.74, budExtCost:4778.96, budHiComm:477.9, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:4778.96, balHiComm:477.9, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UMB-01", desc:"G-Plate Stack Combo 400lbs", isShip:false, budQty:3.0, unit:"ea", budUnitCost:1267.65, budExtCost:3802.95, budHiComm:380.3, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:3802.95, balHiComm:380.3, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UMB-02", desc:"In-Ground Security Mount Anchor (Cantilever - Pool Deck Main)", isShip:false, budQty:6.0, unit:"ea", budUnitCost:354.38, budExtCost:2126.28, budHiComm:212.63, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:2126.28, balHiComm:212.63, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UMB-04", desc:"Aluma-Crete Anchor 150lbs (Wheels)", isShip:false, budQty:5.0, unit:"ea", budUnitCost:492.08, budExtCost:2460.4, budHiComm:246.04, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:2460.4, balHiComm:246.04, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UMB-05", desc:"G-Plate Stack Combo 600lbs (Cantilever - Members Area)", isShip:false, budQty:10.0, unit:"ea", budUnitCost:1723.28, budExtCost:17232.8, budHiComm:1723.28, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:17232.8, balHiComm:1723.28, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UMB-06", desc:"Aluma-Crete Anchor 150lbs (Wheels) - White Finish", isShip:false, budQty:10.0, unit:"ea", budUnitCost:437.4, budExtCost:4374.0, budHiComm:437.4, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:4374.0, balHiComm:437.4, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UMB-07", desc:"Aluma-Crete Anchor 150lbs (Wheels) - Aluma Teak Finish", isShip:false, budQty:20.0, unit:"ea", budUnitCost:492.08, budExtCost:9841.6, budHiComm:984.16, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:9841.6, balHiComm:984.16, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"UMB-11", desc:"Aluma-Crete Anchor 150lbs (Wheels) - White Finish Flex Area", isShip:false, budQty:4.0, unit:"ea", budUnitCost:437.4, budExtCost:1749.6, budHiComm:174.96, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:1749.6, balHiComm:174.96, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"WT-01", desc:"Cabana Curtains for Existing Cabanas (per side)", isShip:false, budQty:3.0, unit:"ea", budUnitCost:826.2, budExtCost:2478.6, budHiComm:247.86, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:2478.6, balHiComm:247.86, status:"Not Started", eta:"", notes:""},
  {vendor:"TUUCI", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:31612.41, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:31612.41, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // WALTERS WICKER
  // ──────────────────────────────────────────────────────
  {vendor:"WALTERS WICKER", code:"TB-06", desc:"Side Table", isShip:false, budQty:70.0, unit:"ea", budUnitCost:298.0, budExtCost:20860.0, budHiComm:2086.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:20860.0, balHiComm:2086.0, status:"Not Started", eta:"", notes:""},
  {vendor:"WALTERS WICKER", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:2086.0, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:2086.0, balHiComm:0.0, status:"Not Started", eta:"", notes:""},

  // ──────────────────────────────────────────────────────
  // WEST ELM
  // ──────────────────────────────────────────────────────
  {vendor:"WEST ELM", code:"AC-18", desc:"Planters Pot (13\"x9\")", isShip:false, budQty:2.0, unit:"ea", budUnitCost:71.2, budExtCost:142.4, budHiComm:14.24, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0.0, balVendor:142.4, balHiComm:14.24, status:"Not Started", eta:"", notes:""},
  {vendor:"WEST ELM", code:"SHIP", desc:"Shipping", isShip:true, budQty:0, unit:"ea", budUnitCost:0, budExtCost:14.24, budHiComm:0.0, actQty:0, actUnitCost:0, actExtCost:0, actHiComm:0.0, commPaid:"No", paidVendor:0.0, commPaidAmt:0, balVendor:14.24, balHiComm:0.0, status:"Not Started", eta:"", notes:""},
];

const PROJECT_FIXED = {
  storage_installation: 75000.00,
  blondies_shipping_credit: -24528.00,
  sales_tax_rate: 0.07,
  shipping_rate: 0.10,
  commission_rate: 0.10,
};
